### PR TITLE
add typings and node_modules to gitignore

### PR DESCRIPTION
**Pull request by joprice**

### CODE REVIEW

**Comment by xealot** [comment]
On typical RE projects we commit typings, node_modules def no.

**Comment by joprice** [comment]
These both showed up after `npm install`, so I assumed they were build artifacts.

**Comment by xealot** [comment]
This project does have a postinstall script in package.json that does this, however it's convenient to commit the typings since there isn't really a downside to not doing it so we do.

Additionally, in the future (and in current projects) types are imported using plain npm package dependencies in the form of `@types/XXX`

**Comment by joprice** [comment]
I pushed another commit that adds the typings and removes the gitignore line.

**Comment by joprice** [comment]
Do you know how to build this? I've only worked with ts in a limited fashion using the compiler directly, or an ide. This seems to be a mixed bag, where the gulp file assumes some other step to be run first (or the gulp file is outdated).

**Comment by xealot** [comment]
Glanced at the gulpfile... not terrible sure. 

We typically just run `tsc -w`, but I don't know what kind of loader/builder is being employed here off hand.

**Comment by joprice** [comment]
Shit. That produced a barrage of js and source map files. Is there no concept of a target folder?

**Comment by xealot** [comment]
Haha, we normally put everything inside of a `dist` folder... Taking a quick glance at `tsconfig.json` I don't see any settings there... 

George might have to weigh in, this wouldn't be my decision... Is `master` the right branch?

**Comment by joprice** [comment]
Master is the only branch.

**Comment by joprice** [comment]
I'll ask him to add a readme to this (unless we're intentionally shooting for a low bus factor). Seems like there's some manual steps that haven't been automated yet.

**Comment by joprice** [comment]
https://adamprescott.files.wordpress.com/2012/12/busfactor1.png

**Comment by xealot** [comment]
Do we want low... or high bus factor? I'm not sure anymore.

**Comment by joprice** [comment]
High, unless you have some legacy you want to shed.

**Comment by joprice** [comment]
It seems some people (https://github.com/zats/github_bus_factor) do it not but count of what it would take to kill the project, but likelihood, then it's the opposite:

screen shot 2016-10-29 at 6 18 55 pm

**Comment by xealot** [comment]
Oh man, what a world! There is a tool for everything.

**Pull request merged**
